---
name: Release Builds
#on:
#  push:
#    tags:
#      - v*

on:
  push:
    branches: [ main ]

jobs:
  build-package-release:
    name: "Prepare release version"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - name: clean with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean
      - name: publishToMavenLocal with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToMavenLocal
      - name: Upload Maven Local
        uses: actions/upload-artifact@v2
        with:
          name: gradle-package-linux
          path: ~/.m2/repository/com/github/specmesh/
      - name: publish Native to GitHub Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishNativePublicationToGitHubPackagesRepository
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}